# Привет! Это конфиг плагина 9l10h (Nine Lives Ten Hearts)
# Здесь можно настроить режим игры и дополнительные параметры, отвечающие за работоспособность механик.
# Plugin by Kryaznov

# ─────────────────────────────────────────────────────────────
# 🎮 Режим игры: "hard" / "immortal"
# "hard" - Игроки теряют сердца. При потере всех сердец → режим наблюдателя (гм 3).
#          Возможность воскрешения командой: /9l resurrect {player} {Число сердец}
# "immortal" - Игроки теряют сердца, но не могут потерять последнее сердце.
# ─────────────────────────────────────────────────────────────
gamemode: hard

# ─────────────────────────────────────────────────────────────
# Настройка числа сердец
# ─────────────────────────────────────────────────────────────
hearts:
  default: 10      # сколько сердец получает новый игрок по умолчанию
  max: 10      # максимально разрешённое число сердец в игре

# Когда у игрока станет 0 сердец, выполняем эти команды под консолью.
# {player} будет автоматически заменён на имя игрока.
on-zero-hearts:
  commands:
    - "gamemode {player} spectator"
    - "tellraw {player} {\"text\":\"У вас закончились все жизни!\",\"color\":\"red\"}"
    # пример бана:
    # - "ban {player} Вы исчерпали все жизни!"


# ─────────────────────────────────────────────────────────────
# Восстановление сердец
# ─────────────────────────────────────────────────────────────
heart-recovery:

  # Восстановление через уникальный тотем
  totem:
    enabled: true                # Включить механику тотемов
    container: 12345              # CustomModelData (если используется ресурс-пак)
    name: "&#55FA33Уникальный Тотем"
    lore:
      - "&#55FA33Умри с этим тотемом в руках,"
      - "&#55FA33чтобы получить дополнительное здоровье"

  # Восстановление через еду (по умолчанию - зачарованное золотое яблоко)
  eat:
    enabled: true                # Включить механику восстановления через еду
    food: "ENCHANTED_GOLDEN_APPLE" # Тип еды (по умолчанию - зачарованное золотое яблоко)

# ─────────────────────────────────────────────────────────────
# Механика выпадения "головы"
# ─────────────────────────────────────────────────────────────
head-heart:
  enabled: true                  # Включить механику выпадения голов игроков
  only-player-kill: true   # только при убийстве игроком
  drop-chance: 1.00        # шанс дропа головы в общем
  name: "&#55FA33Выпавшее сердце игрока {player}"
  lore:
    - "&#55FA33Нажми ПКМ с этим предметом в руках"
    - "&#55FA33чтобы восстановить одно сердце"
  value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWI3NmI0ZWU5ODg1NzIyOTdjYmQ4NzQ2ODNiZWU5NmFlM2M1NWNlOTRjMDA0ZTUxYWRjODJjZWUxNmNkMGIwYyJ9fX0="
  container: 12345                # CustomModelData для уникальных текстур

  # ─────────────────────────────────────────────────────────────
  # Механика выпадения "проклятой головы" - можно сделать одинаковые lore для пущего эффекта
  # ─────────────────────────────────────────────────────────────
  cursed:
    enabled: true
    chance: 0.05           # шанс вместо обычной получить «проклятую голову»
    amount-heart: 1        # сколько сердец отбирает при использовании
    name: "&#551111Проклятая голова {player}"
    lore:
      - "&#551111Нажми ПКМ — потеряешь {amount} сердце"
    value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWI3NmI0ZWU5ODg1NzIyOTdjYmQ4NzQ2ODNiZWU5NmFlM2M1NWNlOTRjMDA0ZTUxYWRjODJjZWUxNmNkMGIwYyJ9fX0="
    container: 12346
